<?
// ID USUARIO PROCESO AUTOMATICO PARA LOGGER
define(USUARIO_PROCESO_AUTOMATICO, 99999);

// ACCIONES - WEB
define(ALTA_USUARIO_WEB,1);
define(BAJA_USUARIO_WEB,2);
define(MODIFICACION_USUARIO_WEB,3);
define(CAMBIO_CONFIGURACION_SISTEMA,4);

?>